# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mnemo', models.CharField(max_length=15, unique=True, verbose_name='Mnemonique')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('naissance', models.DateField(verbose_name='Date de naissance')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Solde')),
                ('sexe', models.CharField(choices=[('HO', 'Homme'), ('FE', 'Femme')], max_length=2)),
                ('niveau', models.CharField(choices=[('MINI', 'MINI'), ('NOVICE', 'NOVICE'), ('TOP', 'TOP')], max_length=7)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], max_length=5)),
            ],
        ),
    ]
