# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateDedmande', models.DateField(auto_now=True, verbose_name='Date de la demande')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Montant de la demande')),
                ('dateReponse', models.DateField(verbose_name='Date de réponse')),
                ('accepte', models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=2)),
                ('clientDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientsDemandeurs', to='client.Client', verbose_name='Client demandeur')),
                ('clientReceveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClientsReceveurs', to='client.Client', verbose_name='Client receveur')),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Mode', verbose_name='Mode de paiement'),
        ),
    ]
