# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160427_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='accepte',
            field=models.CharField(blank=True, choices=[('OUI', 'Oui'), ('NON', 'Non')], max_length=2),
        ),
    ]
