# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20160427_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='dateDedmande',
            new_name='dateDemande',
        ),
    ]
