# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('sousCategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congelateur.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Congelateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('emplacement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Glace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prixVente', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fournisseur', models.CharField(choices=[('AD', 'Admin')], default='AD', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tiroir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('congelateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congelateur.Congelateur')),
            ],
        ),
        migrations.AddField(
            model_name='bac',
            name='tiroir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congelateur.Tiroir'),
        ),
    ]
