# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0004_auto_20160329_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='congelateur',
            name='nombreDeBac',
            field=models.IntegerField(default=5, verbose_name='Nombre de bacs'),
            preserve_default=False,
        ),
    ]
