# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0006_auto_20160329_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congelateur',
            name='nombreDeBac',
        ),
    ]
