# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0008_auto_20160330_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glace',
            name='cat',
        ),
    ]
