# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0009_remove_glace_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glace',
            name='bac',
        ),
    ]
