# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:50
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0012_auto_20160330_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='glace',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/products'), upload_to='', verbose_name='Image'),
        ),
    ]
