# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0016_auto_20160408_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Image'),
        ),
    ]
