# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0018_auto_20160413_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glace',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glaces', to='congelateur.Categorie', verbose_name='Catégorie de la glace'),
        ),
    ]
