# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congelateur', '0019_auto_20160422_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='sousCategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='congelateur.Categorie', verbose_name='Catégorie'),
        ),
    ]
