# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congelateur', '0020_auto_20160427_1040'),
        ('client', '0006_auto_20160427_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Montant de la ligne')),
                ('glace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glaces', to='congelateur.Glace', verbose_name='Glace de la transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code transaction')),
                ('type', models.CharField(choices=[('A', 'Achat'), ('R', 'Réapprovisionnement')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transactions', verbose_name='Image')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client.Client', verbose_name='Client de la transaction')),
            ],
        ),
        migrations.AddField(
            model_name='lignetransaction',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='transaction.Transaction', verbose_name='Ligne transaction'),
        ),
    ]
